/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_2edd;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Nicolás Briceño
 */
public class Interfaz_Proyecto2 extends javax.swing.JFrame {
    public UserList list = new UserList();
    public archivo txt = new archivo();
    
    /**
     * Creates new form Interfaz_Proyecto2
     */
    public Interfaz_Proyecto2() {
        initComponents();
        boxprioridades.removeAllItems();
        boxprioridades.addItem("prioridad_baja");
        boxprioridades.addItem("prioridad_media");
        boxprioridades.addItem("prioridad_alta");
        boxelimuser.removeAllItems();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        browsebutton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ExploradorArchivo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fieldnewname = new javax.swing.JTextField();
        boxprioridades = new javax.swing.JComboBox<>();
        addbutton = new javax.swing.JButton();
        boxelimuser = new javax.swing.JComboBox<>();
        deletebutton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Inicio");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));

        jTabbedPane1.addTab("Inicio", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        browsebutton.setText("Browse...");
        browsebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browsebuttonActionPerformed(evt);
            }
        });
        jPanel2.add(browsebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 80, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Menu de Usuarios");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        ExploradorArchivo.setText("Cargue archivo de formato \"csv.\"");
        ExploradorArchivo.setEnabled(false);
        ExploradorArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExploradorArchivoActionPerformed(evt);
            }
        });
        jPanel2.add(ExploradorArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 340, -1));

        jTextPane1.setEnabled(false);
        jScrollPane1.setViewportView(jTextPane1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 440, 70));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Ver usuarios existentes");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Eliminar usuario");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Agregar nuevo usuario: inserte nombre y nivel de prioridad");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Cargar archivo con la información");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 30));

        fieldnewname.setText("Inserte nombre de Usuario");
        jPanel2.add(fieldnewname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 200, -1));

        boxprioridades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(boxprioridades, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 130, -1));

        addbutton.setText("Agregar");
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(addbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 80, -1));

        boxelimuser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(boxelimuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 340, -1));

        deletebutton.setText("Eliminar");
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });
        jPanel2.add(deletebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 80, -1));

        jTabbedPane1.addTab("Usuarios", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("tab3", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Refresh(){
        if(list.getpFirst() == null){
            JOptionPane.showMessageDialog(this, "Primero debe cargar el archivo","ALERTA", JOptionPane.WARNING_MESSAGE);
            return;
        }
        txt.writecsv(list);
        String data = list.Imprimir(list);
        jTextPane1.setText(data);
    }
    
    private void browsebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browsebuttonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        list.setFilepath(filename);
        if(filename.contains(".csv")){
            txt.readcsv(list, list.getFilepath());
            Usuario aux = list.getpFirst();
            while(aux != null){
                boxelimuser.addItem(aux.getNombre());
                aux = aux.getpNext();
            }
            String data = list.Imprimir(list);
            jTextPane1.setText(data);
            ExploradorArchivo.setText("Datos de usuario cargados");
        }else{
            JOptionPane.showMessageDialog(this, "Tipo de archivo no válido","ALERTA", JOptionPane.WARNING_MESSAGE);
            ExploradorArchivo.setText("Tipo de archivo no válido. Se requiere: csv");
        }
    }//GEN-LAST:event_browsebuttonActionPerformed

    private void ExploradorArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExploradorArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExploradorArchivoActionPerformed

    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed
        if(list.getpFirst() == null){
            JOptionPane.showMessageDialog(this, "Primero debe cargar el archivo","ALERTA", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String nu = fieldnewname.getText();
        if(nu.contains(" ")){
            nu = nu.replace(" ", "_");
        }else if(nu.contains("-") || nu.contains("*") || nu.contains("+") || nu.contains("/") || nu.contains("^") || nu.contains("=")){
            JOptionPane.showMessageDialog(this, "Nombre de Usuario no válido"+"\n"+"Revisar: -  *  +  /  ^  =  ;  ,  &  %  |  ()  []  {}","ALERTA", JOptionPane.WARNING_MESSAGE);
            return;
        }else if(nu.contains(";") || nu.contains(",") || nu.contains("&") || nu.contains("%") || nu.contains("|")){
            JOptionPane.showMessageDialog(this, "Nombre de Usuario no válido"+"\n"+"Revisar: -  *  +  /  ^  =  ;  ,  &  %  |  ()  []  {}","ALERTA", JOptionPane.WARNING_MESSAGE);
            return;
        }else if(nu.contains("(") || nu.contains(")") || nu.contains("[") || nu.contains("]") || nu.contains("{") || nu.contains("}")){
            JOptionPane.showMessageDialog(this, "Nombre de Usuario no válido"+"\n"+"Revisar: -  *  +  /  ^  =  ;  ,  &  %  |  ()  []  {}","ALERTA", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String priority = (String)boxprioridades.getSelectedItem();
        list.Insertar(nu, priority);
        boxelimuser.addItem(list.getpLast().getNombre());
        this.Refresh();
    }//GEN-LAST:event_addbuttonActionPerformed

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
        if(list.getpFirst() == null){
            JOptionPane.showMessageDialog(this, "Primero debe cargar el archivo","ALERTA", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String nombre = (String)boxelimuser.getSelectedItem();
        int index = boxelimuser.getSelectedIndex();
        list.Eliminar(nombre);
        boxelimuser.removeItemAt(index);
        this.Refresh();
    }//GEN-LAST:event_deletebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Proyecto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Proyecto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Proyecto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Proyecto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Proyecto2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ExploradorArchivo;
    private javax.swing.JButton addbutton;
    private javax.swing.JComboBox<String> boxelimuser;
    private javax.swing.JComboBox<String> boxprioridades;
    private javax.swing.JButton browsebutton;
    private javax.swing.JButton deletebutton;
    private javax.swing.JTextField fieldnewname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
